---

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php for CentOS
    yum:
     name:
       - httpd
       - php
     state: latest
     update_cache: true
    when: ansible_distribution == "CentOS"
