---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
     name: libapache2-mod-php
     state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update centos repo index
    yum:
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for httpd
    yum:
     name: php
     state: latest
    when: ansible_distribution == "CentOS"
