- hosts: all
  become: true
  pre_tasks:
    - name: install updates CentOS
      tags: always
      yum:
        update_cache: true
        update_only: true
      when: ansible_distribution == "CentOS"
    - name: install updates Ubuntu
      tags: always
      apt:
        update_cache: true
        upgrade: dist
      when: ansible_distribution == "Ubuntu"
- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php packages for Ubuntu
      tags: web,ubuntu,apache,php
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: install httpd and php for CentOS
      tags: web,centos,apache,php
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb on CentOS
    tags: db,centos,mariadb
    yum:
     name:
      - mariadb
     state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb on ubuntu
    tags: db,ubuntu,mariadb
    apt:
     name:
      - mariadb-server
     state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks: 

  - name: install samba package
    tags: file,samba
    package:
     name: samba
     state: latest
