- name: install apache and php packages for Ubuntu
  tags: web,ubuntu,apache,php
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"
- name: install httpd and php for CentOS
  tags: web,centos,apache,php
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"
- name: start httpd (CentOS)
  tags: web,centos,apache
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
- name: change email address for admin*
  tags: apache, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: ^ServerAdmin
    line: ServerAdmin abc@ample.com
  when: ansible_distribution == "CentOS"
  register: state_httpd
- name: restard httpd (CentOS)
  tags: apache, centos, httpd
  service:
    name: httpd
    state: restarted
  when: state_httpd.changed
- name: copy default html file for site
  tags: apache
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 644
