- name: install mariadb on CentOS
  tags: db,centos,mariadb
  yum:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "CentOS"
- name: install mariadb on ubuntu
  tags: db,mariadb,ubuntu
  apt:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
